spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ######
    password: ######
    url: #####
  redis:
    host: ####


wechat:
 mini-app:
  app-id: #######
  app-secret: #####
mybatis:
  config-location: classpath:mytbatis/mybatis.xml
  mapper-locations: classpath:mytbatis/DainaMapper.xml


